{% set name = "biofilm" %}
{% set version = "0.1.124" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/biofilm-{{ version }}.tar.gz
  sha256: 6c36bb00e64df7b87261d28e5dbd1ff4850b2a0146a11a07fe59b5e4431cae94



build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - auto-sklearn >=0.15
    - dirtyopts >=0.0.18
    - eden-kernel >=0.3.1348
    - lmz >=0.1.12
    - numpy >=1.22.0
    - scikit-learn >=0.24.2
    - structout >=0.1.44
    - ubergauss >=0.0.43
    - pynisher <=0.7

test:
  requires:
    - python {{ python_min }}
  imports:
    - biofilm
    - biofilm.algo

about:
  home: https://github.com/smautner/biofilm
  summary: another opts parser
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - smautner
