{% set name = "biofilm" %}
{% set version = "0.0.98" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/biofilm-{{ version }}.tar.gz
  sha256: d7599c12a4dac12c98c4030f65ce1f3f9a03dae2859e8e146c7a744c5e72157f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - auto-sklearn >=0.15
    - dirtyopts >=0.0.18
    - eden-kernel >=0.3.1348
    - lmz >=0.1.12
    - numpy >=1.22.0
    - scikit-learn >=0.24.2
    - structout >=0.1.44
    - ubergauss >=0.0.43
    - pynisher <=0.7

test:
  imports:
    - biofilm
    - biofilm.algo

about:
  home: https://github.com/smautner/biofilm
  summary: another opts parser
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - smautner
